name: InduceReduce
version: 1.0
date: 2018-09-04
description: |
    Unger's algorithm to compute charater tables of finite groups

authors:
    - name: Jonathan Gruber
      url: mailto:gruber@mathemaik.uni-kl.de

maintainers:
    - name: Jonathan Gruber
      url: mailto:gruber@mathemaik.uni-kl.de

GAP: ">= 4.0"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://jonathan-144.github.io/InduceReduce
readme: README.md
packageinfo: https://jonathan-144.github.io/InduceReduce/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://jonathan-144.github.io/InduceReduce/InduceReduce-1.0.tar.gz

abstract: |
    This package provides an implementation of Unger's algorithm to compute the character table of a finite group.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    character table, elementary subgroups, induced characters.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Gru18</span>]   <b class='BibAuthor'>Gruber, J.</b>,
     <i class='BibTitle'>InduceReduce, Unger's algorithm to compute charater tables of finite groups,
             Version 1.0</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://jonathan-144.github.io/InduceReduce">https://jonathan-144.github.io/InduceReduce</a></span>.
    </p>
    

bibtex: |
    @misc{ InduceReduce1.0,
      author =           {Gruber, J.},
      title =            {{InduceReduce},  Unger's algorithm to compute charater
                          tables of finite groups, {V}ersion 1.0},
      month =            {Sep},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href    {https://jonathan-144.github.io/InduceReduce}
                          {\texttt{https://jonathan-144.github.io/}\discretionary
                          {}{}{}\texttt{InduceReduce}}},
      keywords =         {character   table;   elementary   subgroups;   induced
                          characters},
      printedkey =       {Gru18}
    }

