name: InduceReduce
version: "1.3"
license: "GPL-3.0-or-later"
date: 2025-10-16
description: |
    Unger's algorithm to compute character tables of finite groups

authors:
    - name: Jonathan Gruber
      url: mailto:jonathan.gruber@fau.de

maintainers:
    - name: Jonathan Gruber
      url: mailto:jonathan.gruber@fau.de
    - name: Thomas Breuer
      url: https://www.math.rwth-aachen.de/~Thomas.Breuer
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/InduceReduce/
readme: README.md
packageinfo: https://gap-packages.github.io/InduceReduce/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/InduceReduce/releases/download/v1.3/InduceReduce-1.3.tar.gz

abstract: |
    This package provides an implementation of Unger's algorithm to compute the character table of a finite group.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    character table, elementary subgroups, induced characters.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GBH25</span>]   <b class='BibAuthor'>Gruber, J., Breuer, T. and Horn, M.</b>,
     <i class='BibTitle'>InduceReduce, Unger's algorithm to compute character tables of finite groups,
             Version 1.3</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/InduceReduce/">https://gap-packages.github.io/InduceReduce/</a></span>.
    </p>
    

bibtex: |
    @misc{ InduceReduce,
      author =           {Gruber, J. and Breuer, T. and Horn, M.},
      title =            {{InduceReduce},    {Unger's   algorithm   to   compute
                          character tables of finite groups}, {V}ersion 1.3},
      month =            {Oct},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href   {https://gap-packages.github.io/InduceReduce/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{InduceReduce/}}},
      keywords =         {character   table;   elementary   subgroups;   induced
                          characters},
      printedkey =       {GBH25}
    }

